language: python
python: 
    - "3.8"
#To include docker: (Do not know how to incoorporate it yet)
#sudo: required
#services: 
#    - docker
install:
    - pip install -r requirements.txt
branches: 
    only: 
       - master
script:
#Simple python script
    - python firsttest.py

#Flask application
    - python -m unittest tests/test_first_flask_app.py
#Docker