language: python
python: 
    - "3.8"
sudo: required
services: 
    - docker
install:
    - pip install -r first_flask_app/requirements.txt
branches: 
    only: 
       - master
script:
   - python firsttest.py