language: python
python: 
    - "3.8"
env:
    - secure: "UE8YX6HeqQjAj+uy/EQjkLH79+7hBX6JJryNqXPYxot64kJ7JsEysZz1K6btF9tGENzShCrOmCMuBv7Snme/gawY1HHlVDyGqGEecX271c2sfC0vxiazEpfW0EgfABOKvjSORQC6GEuF7N0QaapfnnLN0t+zG0ObHu7Qoc/b3HswwyV+sD7u5vebjuJpQsUvRw1rCUso+Jn/DHXHBWH0lLE87PYSbOdmIoXYGDhgq0tY2kQn6Zja6fdfPz0YP6M7luDfhyTX36yw01yK0inIvfSbmw3k2lVkYFcUNkdqKHWgLqfSYSCThYkrVyLi7QhQx3Ws8n2EaVw2iOYY7r8r420l/hZYyrt4Evm42J1l9QJLzWrHbI0a3HJzg/tsxeXuQSsJ5frXTr0I5wfdDc9GovM+iJOMUE638vE+ozW3hMbHoOmrgDtg2hLmZuR3IXLg2WJ9wYtuO54PTTYYT1r921gsp/Szq6qadkVW01Fi8bAhx7+IWHiP4L0Io2tx7z9U9kjEs86qzQlmN5MWmtY1TNKxbvevi+f5OmMurAE8nGrPKk2mLODy8tyxNCsrlqmGPTd3IYQpsfq3uQzZkBpFZlaX9i0if4cXeFDJBkfUZdfvyM1B10Pb02Zo/fPmvWrMhHmoSB3mRT9K6niTBqynmhipOp6VAKzx36prq7x/8iY="
    - secure: "DkI9RJ3xvHDFXEK8XD9F92JsXicdbWCNY1dlmsMrZmWmuWKdpcR5qgjIrrYn7z0C7NBYHy4msuMBqyqYVUT3TkHvUpeW20z8+4qQ/PUBOvANmYH9HrvmSI05fhiQUJvyOkNcPtvzV+63DuOPhiSiM0lXYgi3H+/FPRHfJaNCVWJAAPuD67v+MThHSFsht7KHFDbcUK7yuDTkUHsryzk9B9/7fK4aXjMqVbGAnLNtzfOlCDoQC8ZiT5cWHi+zWlt6LnPMslAyzKNapaHfOLQyKrruenZjn+AmPkoPlnt8PuJejPN63JId2PB9mDB/Kn3p/kbu8rIVc1vXNOo4i7yM3HNnT1501ptcLEA82O7gJ7T5EKDOBApc+v7QWp+q64sAYvLRjfDkU/uHQwOp33DkIdPbvrGKp6WvsveJ1Vm4w26kGqPGim51iE/IlbmBxTXeZLgYwNAnN2n8mjnf0YJQnT/5Q+qC58UfkeiFoA79n2zzmqvfVZgXRjW8tx3VS0V54nRdJz+UK1nsPERnjUAi9zQIqxaDhS536zaGtsAn1uU4fMWaapOB+vEl7/N+3rfBdLjg58br2pE5dqUPvV0m8th+IB7erAca9bCnoDkhV4wPSw6K9z1pQh0RFpojmMXSH6KiSKDVSiqJ8Gyz5EHoWsXRr49cT/DI2iMT3MCMorQ="
services: 
    - docker 
#Only trigger Travis when pushed to master branch:
branches: 
    only: 
        - master
before_install:
    #Docker
    #Build image and run container
    #This can be moved to script if we want to see status for the build and run
    - cd app
    
    #- docker build -t "test_app_image" . 
    #- docker run -d -p 3000:5000 --name test_app_container test_app_image 
    
    #With docker-compose: 
    - docker-compose up -d --build #Build to make sure the image is built
    - docker ps
    - cd -

#First main phase is install
install:
    - pip install -r requirements.txt

#Second main phase is script
#This is where Travis tests and runs code
script:
#Run code involving content of code:
    - python -m unittest tests/test_structure.py
    - python -m unittest tests/test_content.py 
    #Simple python script can be run like this: 
    #- python firsttest.py
    #Running all tests in a package: 
    # - python -m unittest discover tests 


    #Tests involving the running of web app
    - python -m unittest tests/test_running.py

    #Stop and remove the running container
    - cd app
    - docker ps
    - docker stop $(docker ps -q -f "name=app_container")
    - docker ps

    - docker container rm $(docker ps -a -q -f "name=app_container") #Removes the container
    
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email --region eu-west-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    #- aws ecr get-login-password | docker login  --password-stdin --username AWS "459994320734.dkr.ecr.eu-west-1.amazonaws.com"
    - docker build -t app_image:latest .
    - docker tag app_image:latest 459994320734.dkr.ecr.eu-west-1.amazonaws.com/app-image-repo
    - docker push 459994320734.dkr.ecr.eu-west-1.amazonaws.com/app-image-repo:latest
 
#Additional actions?
#after_success:
#after_failure:
#deploy:
#    provider: script
#    script: bash push-to-aws.sh