language: python
python: 
    - "3.8"
services: 
    - docker 
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
script:
    - bash run-docker-and-tests.sh
deploy:
    provider: script
    script: bash push-to-aws.sh