language: python
python: 
    - "3.8"
services: 
    - docker 
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
script:
    - bash run-docker-and-tests.sh
    - current_dir=$PWD
    - app_name="${current_dir%"${current_dir##*[!/]}"}" # extglob-free multi-trailing-/ trim
    - app_name="${app_name##*/}"
    - echo "$app_name"
#deploy:
#    provider: script
#    script: bash push-to-aws.sh