language: python
python: 
    - "3.8"
services: 
    - docker 
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
script:
    - bash run-docker-and-tests.sh
    - source AWS-env-var.sh
    - cd app
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - export AWS_ACCOUNT_ID= "$( aws sts get-caller-identity --output text --query 'Account' )"
    - echo "${AWS_ACCOUNT_ID}"
    - docker build -t $AWS_IMAGE_NAME:latest .
    - docker tag "${AWS_IMAGE_NAME}":latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_REPO
    - docker push "${AWS_ACCOUNT_ID}".dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_REPO:latest
#deploy:
#    provider: script
#    script: bash push-to-aws.sh