language: python
python: 
    - "3.8"
services: 
    - docker 
#First main phase is install
install:
    - pip install -r requirements.txt
#Only trigger Travis when pushed to master branch:
branches: 
    only: 
       - master
#Second main phase is script
script:
#This is where Travis tests and runs code
#Simple python script
    - python firsttest.py

#Running package of tests checking code not connected to running applications/containers
   # - python -m unittest discover tests  

#Docker
    - cd first_flask_app
    - docker build -t "first_flask_app_image" . 
    - docker run -d -p 5000:5000 --name first_flask_app_container first_flask_app_image 
    - docker ps
    #Running test, including those involving if application is running
    - cd -
    - python -m unittest discover tests
    - cd first_flask_app

    - docker stop $(docker ps -q -f "name=first_flask_app_container")
    - docker ps
    - docker container rm $(docker ps -a -q -f "name=first_flask_app_container")
    - cd -

#Additional actions?
#after_success:
#after_failure:
#deploy: