language: python
python: 
    - "3.8"
services: 
    - docker 
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
script:
    #- docker ps | grep app_container #Testing that the container is running
    #- python -m unittest discover tests #Running unittests
    - source run-docker-and-tests.sh
deploy:
    provider: script
    script: bash push-to-aws.sh