language: python
python: 
    - "3.8"
services: 
    - docker 
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
    - bash run-docker.sh
script:
    - python -m unittest discover tests 
after_script:
    - stop-docker.sh
#deploy:
#    provider: script
#    script: bash push-to-aws.sh