language: python
python: 
    - "3.8"
services: 
    - docker 
#Only trigger Travis when pushed to master branch:
branches: 
    only: 
        - master
install:
    - pip install -r requirements.txt
script:
    - python -m unittest tests/test_structure.py