version: '3'
services:
  app:
    build: .
    image: app_image:test
    ports:
      - "3000:4000" #The container port must match the gunicorn or app port
    container_name: app_container #This name is used in .travis.yml